--
-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."courses" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."courses" OWNER TO "postgres";

--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."courses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."courses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hole_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."hole_info" (
    "tee_box_id" bigint NOT NULL,
    "hole_number" smallint NOT NULL,
    "par" smallint NOT NULL,
    "yardage" smallint NOT NULL,
    "handicap" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."hole_info" OWNER TO "postgres";

--
-- Name: hole_scores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."hole_scores" (
    "scorecard_id" bigint NOT NULL,
    "hole_number" smallint NOT NULL,
    "score" smallint
);


ALTER TABLE "public"."hole_scores" OWNER TO "postgres";

--
-- Name: players; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."players" (
    "id" bigint NOT NULL,
    "handicap" real,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."players" OWNER TO "postgres";

--
-- Name: players_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."players" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."players_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rounds; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."rounds" (
    "id" bigint NOT NULL,
    "trip_id" bigint NOT NULL,
    "course_id" bigint NOT NULL,
    "date" date,
    "name" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."rounds" OWNER TO "postgres";

--
-- Name: rounds_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."rounds" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rounds_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scorecards; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."scorecards" (
    "id" bigint NOT NULL,
    "player_id" bigint NOT NULL,
    "round_id" bigint NOT NULL,
    "tee_box_id" bigint NOT NULL,
    "player_handicap" real,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."scorecards" OWNER TO "postgres";

--
-- Name: scorecards_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."scorecards" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."scorecards_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tee_boxes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."tee_boxes" (
    "id" bigint NOT NULL,
    "course_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "rating" real NOT NULL,
    "slope" real NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."tee_boxes" OWNER TO "postgres";

--
-- Name: tee_box_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."tee_boxes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tee_box_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trip_players; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."trip_players" (
    "trip_id" bigint NOT NULL,
    "player_id" bigint NOT NULL
);


ALTER TABLE "public"."trip_players" OWNER TO "postgres";

--
-- Name: trips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."trips" (
    "id" bigint NOT NULL,
    "name" "text",
    "start_date" "date",
    "end_date" "date"
);


ALTER TABLE "public"."trips" OWNER TO "postgres";

--
-- Name: trips_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."trips" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."trips_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."courses"
    ADD CONSTRAINT "courses_pkey" PRIMARY KEY ("id");


--
-- Name: hole_info hole_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."hole_info"
    ADD CONSTRAINT "hole_info_pkey" PRIMARY KEY ("tee_box_id", "hole_number");


--
-- Name: hole_scores hole_scores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."hole_scores"
    ADD CONSTRAINT "hole_scores_pkey" PRIMARY KEY ("scorecard_id", "hole_number");


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");


--
-- Name: rounds rounds_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."rounds"
    ADD CONSTRAINT "rounds_pkey" PRIMARY KEY ("id");


--
-- Name: scorecards scorecards_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."scorecards"
    ADD CONSTRAINT "scorecards_pkey" PRIMARY KEY ("id");


--
-- Name: tee_boxes tee_box_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."tee_boxes"
    ADD CONSTRAINT "tee_box_pkey" PRIMARY KEY ("id");


--
-- Name: trip_players trip_players_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."trip_players"
    ADD CONSTRAINT "trip_players_pkey" PRIMARY KEY ("trip_id", "player_id");


--
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."trips"
    ADD CONSTRAINT "trips_pkey" PRIMARY KEY ("id");


--
-- Name: hole_info hole_info_tee_box_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."hole_info"
    ADD CONSTRAINT "hole_info_tee_box_id_fkey" FOREIGN KEY ("tee_box_id") REFERENCES "public"."tee_boxes"("id");


--
-- Name: hole_scores hole_scores_scorecard_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."hole_scores"
    ADD CONSTRAINT "hole_scores_scorecard_id_fkey" FOREIGN KEY ("scorecard_id") REFERENCES "public"."scorecards"("id");


--
-- Name: rounds rounds_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."rounds"
    ADD CONSTRAINT "rounds_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("id");


--
-- Name: rounds rounds_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."rounds"
    ADD CONSTRAINT "rounds_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id");


--
-- Name: scorecards scorecards_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."scorecards"
    ADD CONSTRAINT "scorecards_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id");


--
-- Name: scorecards scorecards_round_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."scorecards"
    ADD CONSTRAINT "scorecards_round_id_fkey" FOREIGN KEY ("round_id") REFERENCES "public"."rounds"("id");


--
-- Name: scorecards scorecards_tee_box_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."scorecards"
    ADD CONSTRAINT "scorecards_tee_box_id_fkey" FOREIGN KEY ("tee_box_id") REFERENCES "public"."tee_boxes"("id");


--
-- Name: tee_boxes tee_boxes_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."tee_boxes"
    ADD CONSTRAINT "tee_boxes_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("id");


--
-- Name: trip_players trip_players_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."trip_players"
    ADD CONSTRAINT "trip_players_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id");


--
-- Name: trip_players trip_players_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."trip_players"
    ADD CONSTRAINT "trip_players_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id");


--
-- Name: courses; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."courses" ENABLE ROW LEVEL SECURITY;

--
-- Name: hole_info; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."hole_info" ENABLE ROW LEVEL SECURITY;

--
-- Name: hole_scores; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."hole_scores" ENABLE ROW LEVEL SECURITY;

--
-- Name: players; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."players" ENABLE ROW LEVEL SECURITY;

--
-- Name: rounds; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."rounds" ENABLE ROW LEVEL SECURITY;

--
-- Name: scorecards; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."scorecards" ENABLE ROW LEVEL SECURITY;

--
-- Name: tee_boxes; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."tee_boxes" ENABLE ROW LEVEL SECURITY;

--
-- Name: trip_players; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."trip_players" ENABLE ROW LEVEL SECURITY;

--
-- Name: trips; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."trips" ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA "public"; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


--
-- Name: TABLE "courses"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."courses" TO "postgres";
GRANT ALL ON TABLE "public"."courses" TO "anon";
GRANT ALL ON TABLE "public"."courses" TO "authenticated";
GRANT ALL ON TABLE "public"."courses" TO "service_role";


--
-- Name: SEQUENCE "courses_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."courses_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."courses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."courses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."courses_id_seq" TO "service_role";


--
-- Name: TABLE "hole_info"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."hole_info" TO "postgres";
GRANT ALL ON TABLE "public"."hole_info" TO "anon";
GRANT ALL ON TABLE "public"."hole_info" TO "authenticated";
GRANT ALL ON TABLE "public"."hole_info" TO "service_role";


--
-- Name: TABLE "hole_scores"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."hole_scores" TO "postgres";
GRANT ALL ON TABLE "public"."hole_scores" TO "anon";
GRANT ALL ON TABLE "public"."hole_scores" TO "authenticated";
GRANT ALL ON TABLE "public"."hole_scores" TO "service_role";


--
-- Name: TABLE "players"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."players" TO "postgres";
GRANT ALL ON TABLE "public"."players" TO "anon";
GRANT ALL ON TABLE "public"."players" TO "authenticated";
GRANT ALL ON TABLE "public"."players" TO "service_role";


--
-- Name: SEQUENCE "players_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "service_role";


--
-- Name: TABLE "rounds"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."rounds" TO "postgres";
GRANT ALL ON TABLE "public"."rounds" TO "anon";
GRANT ALL ON TABLE "public"."rounds" TO "authenticated";
GRANT ALL ON TABLE "public"."rounds" TO "service_role";


--
-- Name: SEQUENCE "rounds_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."rounds_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."rounds_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rounds_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rounds_id_seq" TO "service_role";


--
-- Name: TABLE "scorecards"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."scorecards" TO "postgres";
GRANT ALL ON TABLE "public"."scorecards" TO "anon";
GRANT ALL ON TABLE "public"."scorecards" TO "authenticated";
GRANT ALL ON TABLE "public"."scorecards" TO "service_role";


--
-- Name: SEQUENCE "scorecards_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."scorecards_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."scorecards_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."scorecards_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."scorecards_id_seq" TO "service_role";


--
-- Name: TABLE "tee_boxes"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."tee_boxes" TO "postgres";
GRANT ALL ON TABLE "public"."tee_boxes" TO "anon";
GRANT ALL ON TABLE "public"."tee_boxes" TO "authenticated";
GRANT ALL ON TABLE "public"."tee_boxes" TO "service_role";


--
-- Name: SEQUENCE "tee_box_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."tee_box_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."tee_box_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tee_box_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tee_box_id_seq" TO "service_role";


--
-- Name: TABLE "trip_players"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."trip_players" TO "postgres";
GRANT ALL ON TABLE "public"."trip_players" TO "anon";
GRANT ALL ON TABLE "public"."trip_players" TO "authenticated";
GRANT ALL ON TABLE "public"."trip_players" TO "service_role";


--
-- Name: TABLE "trips"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."trips" TO "postgres";
GRANT ALL ON TABLE "public"."trips" TO "anon";
GRANT ALL ON TABLE "public"."trips" TO "authenticated";
GRANT ALL ON TABLE "public"."trips" TO "service_role";


--
-- Name: SEQUENCE "trips_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."trips_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."trips_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trips_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trips_id_seq" TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";
